import {Navbar} from "../components/Navbar";
import {WorkspacePreview} from "../components/WorkspacePreview";
import {AgentsShowcase} from "../components/AgentsShowcase";
import {ParallelAgents} from "../components/ParallelAgents";
import {CustomizeWorkspace} from "../components/CustomizeWorkspace";
import {ThemeShowcase} from "../components/ThemeShowcase";
import {InteractiveLayer} from "../components/InteractiveLayer";
import {ProductDemo} from "../components/ProductDemo";

const steps = [
  ["01", "Téléchargez ScalAI", "Installez l’application et ouvrez-la sur votre ordinateur."],
  ["02", "Choisissez votre dossier", "Pointez ScalAI vers le dossier sur lequel vous voulez travailler."],
  ["03", "Lancez votre première session", "Décrivez simplement ce que vous voulez faire. Votre agent se met au travail."],
];

export default function Home(){return <main>
  <Navbar/><InteractiveLayer/>
  <section className="px-5 pb-20 pt-36 md:pb-28 md:pt-48"><div className="mx-auto max-w-5xl text-center"><p className="rise text-xs font-bold tracking-[.22em] text-black/45">TOUS VOS AGENTS IA. UN SEUL ESPACE.</p><h1 className="font-display rise d1 mt-5 text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-7xl md:text-8xl">Faites travailler<br/>vos agents IA.</h1><p className="rise d2 mx-auto mt-7 max-w-2xl text-base leading-7 text-black/60 sm:text-lg">Réunissez vos agents IA dans un seul espace de travail. Lancez plusieurs tâches en parallèle, travaillez sur vos propres fichiers et passez d’un agent à l’autre sans repartir de zéro.</p><div className="rise d3 mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="#telecharger" className="rounded-full bg-[var(--accent)] px-7 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[var(--accent-dark)]">Télécharger ScalAI</a><a href="#demo" className="rounded-full border border-black/10 bg-white px-7 py-3.5 text-sm font-bold hover:bg-black/[.035]">Découvrir comment ça marche</a></div></div></section>
  <section id="workspace" className="px-5 pb-20"><WorkspacePreview/></section>
  <section id="demo" className="mx-auto max-w-6xl px-5 py-24 md:py-32"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.2em] text-black/40">ESSAYEZ L’EXPÉRIENCE</p><h2 className="font-display mt-4 text-4xl font-extrabold tracking-[-.04em] sm:text-6xl">Un aperçu de ScalAI, avant même de l’installer.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/60">Sélectionnez un agent, lancez une mission, observez les sessions progresser et comparez leurs résultats. Cette démonstration reproduit l’expérience du workspace sans prétendre remplacer encore l’application desktop.</p></div><ProductDemo/></section>
  <section id="agents" className="mx-auto max-w-6xl px-5 py-28 md:py-36"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.2em] text-black/40">TOUS VOS AGENTS, AU MÊME ENDROIT</p><h2 className="font-display mt-4 text-4xl font-extrabold tracking-[-.04em] sm:text-6xl">Lancez vos agents en un clic.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/60">Claude Code, Codex, Antigravity et les autres. Gardez vos agents préférés à portée de main et lancez-les directement dans votre espace de travail.</p></div><AgentsShowcase/></section>
  <section id="parallele" className="mx-auto max-w-6xl px-5 py-28 md:py-36"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.2em] text-black/40">TOUS EN MÊME TEMPS</p><h2 className="font-display mt-4 text-4xl font-extrabold tracking-[-.04em] sm:text-6xl">Une matinée de travail dans le temps qu’il fallait pour une seule tâche.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/60">Lancez plusieurs agents sur la même mission, laissez-les travailler en parallèle et comparez leurs résultats sans changer de fenêtre.</p></div><ParallelAgents/></section>
  <section id="personnalisez" className="bg-[#171717] px-5 py-28 text-white md:py-36"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold tracking-[.2em] text-white/40">FAITES-LE À VOTRE MANIÈRE</p><h2 className="font-display mt-4 max-w-3xl text-4xl font-extrabold tracking-[-.04em] sm:text-6xl">Décrivez un agent. Obtenez un agent.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/55">Personnalisez vos agents, choisissez votre dossier de travail et adaptez l’espace à votre façon de travailler.</p><CustomizeWorkspace/></div></section>
  <section id="themes" className="mx-auto max-w-6xl px-5 py-28 md:py-36"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.2em] text-black/40">UN ESPACE QUI VOUS RESSEMBLE</p><h2 className="font-display mt-4 text-4xl font-extrabold tracking-[-.04em] sm:text-6xl">Clair quand vous voulez. Sombre quand vous préférez.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/60">Choisissez l’apparence qui vous convient. Le workspace, les sessions, les fichiers et les contrôles suivent le même thème pour garder une interface cohérente.</p></div><ThemeShowcase/></section>
  <section id="telecharger" className="download-section border-y border-black/[.07] bg-white px-5 py-28 md:py-36"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold tracking-[.2em] text-black/40">METTEZ-LE SUR VOTRE BUREAU</p><h2 className="font-display mt-4 text-4xl font-extrabold tracking-[-.045em] sm:text-6xl">Commencez avec une seule tâche.</h2><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-black/60">Téléchargez ScalAI, choisissez votre espace de travail et lancez votre première session.</p><a href="#" className="mt-9 inline-flex rounded-full bg-[var(--accent)] px-8 py-4 text-sm font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-[var(--accent-dark)]">Télécharger ScalAI</a></div><div className="mt-20 grid gap-4 md:grid-cols-3">{steps.map(([num,title,text])=><div key={num} className="rounded-3xl border border-black/[.08] bg-[#f8f7f3] p-7"><span className="font-mono text-xs font-bold text-black/35">{num}</span><h3 className="font-display mt-8 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-black/55">{text}</p></div>)}</div></div></section>
  <footer className="px-5 py-10"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-7 border-b border-black/[.08] pb-9 md:flex-row md:items-start md:justify-between"><div><b className="font-display text-xl tracking-[-.04em]">ScalAI</b><p className="mt-3 max-w-xs text-sm leading-6 text-black/45">Tous vos agents IA. Un seul espace de travail.</p></div><div className="grid grid-cols-2 gap-x-14 gap-y-3 text-sm text-black/55"><a href="#agents" className="hover:text-black">Agents</a><a href="#parallele" className="hover:text-black">Fonctionnement</a><a href="#personnalisez" className="hover:text-black">Personnalisez</a><a href="#themes" className="hover:text-black">Thèmes</a><a href="#telecharger" className="hover:text-black">Télécharger</a><a href="#workspace" className="hover:text-black">Workspace</a></div></div><div className="flex flex-col gap-2 pt-7 text-xs text-black/35 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 ScalAI</span><span>Un espace. Plusieurs agents. Votre travail.</span></div></div></footer>
</main>}
